spring.application.name=backend
# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/poke_guess
spring.datasource.username=postgres
spring.datasource.password=sua_senha

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect